name: "Podcast Generator"
author: "Duck Zig"
description: "some description...."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{github.actor}}